version: '3'

services:
  web-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Монтируем локальный код в контейнер
    depends_on:
      - memcached

  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - web-app
