version: '3'

services:
  web-app:
    build: .
    expose:
      - "5000"
    volumes:
      - ./app:/app
    depends_on:
      - memcached

  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  nginx-proxy:
    image: nginx:latest
    ports:
      - "1080:80"
      - "1443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - web-app
